### ISSUE TITLE
Update README.md file with given below instructions

### ISSUE THREAD

**Issue by JohnJenison** [JohnJenison/Covid-19-Dashboard#1]
The file should contain:
1. Description of the project.
2. Tools used: Node js, HTML, CSS, Javascript, Vs Code, and NPM.
3. API Used: Link of the website (https://api.covid19tracker.ca/docs/1.0/overview).
4. Installation details of the tools.
5. Licensing.

**Comment by MaiShantanuHu** [comment]
Hey!! I can do this for you. I have good knowledge of the Markup language and I have also created some good README files for my own projects. You can check some of them on my profile.

**Comment by JohnJenison** [comment]
Thank you for your interest you can submit it by today.
