### ISSUE TITLE
update dashboard.html file

### ISSUE THREAD

**Issue by JohnJenison** [JohnJenison/Covid-19-Dashboard#3]
Create a html page where we can have a dashboard like design with 4 grids. 
1st grid: should have total cases information.
2nd grid: should have total deaths  information.
3rd grid: should have total vaccines available.
4th grid: should have total vaccines distributed.

just put random numbers in the code.

**Comment by Harsh-Singh-Rajput** [comment]
hello @JohnJenison  should i do this?

**Comment by MaiShantanuHu** [comment]
Hii!! I can do this as well, as I did for the README file.

**Comment by biohazard2117** [comment]
Hello @JohnJenison maybe I can give it try. I will try my best. And would try to finish it as fast as possible. 
Looking forward to work on this.
