### ISSUE TITLE
create js file with API Call

### ISSUE THREAD

**Issue by JohnJenison** [JohnJenison/Covid-19-Dashboard#4]
# Task
1. Create "index.js" named file.
2. Call 1st API to get information of total cases and deaths in india (https://covid-api.mmediagroup.fr/v1/cases?country=India).
3. Call 2nd API to get information of total vaccinated and partial vaccinated in india 
    (https://covid-api.mmediagroup.fr/v1/vaccines?country=India).
4. Lastly show these data in dashboard.html file with respected id names.

**Comment by Thunderbolt9** [comment]
Hello, I have created few projects on APIs and would like to contribute to this issue.
